#!/bin/bash

# Copy ~/bin

copy_bin_scripts()
{
	bin_directory=`echo ~/bin`

	cp ./$1/$1 $bin_directory/$1 
}

export -f copy_bin_scripts

cat ./scripts-to-pc.txt | parallel --max-args 1 copy_bin_scripts {}
