#!/bin/bash

# Copy ~/bin

bin_directory=`echo ~/bin`

copy_bin_scripts()
{
	file=`echo "$1" | cut -f 1 -d '.'`

	[ ! -d $file ] && mkdir $file

	cp $bin_directory/$1 ./$1/$1

	echo "Copied $1"
}

export bin_directory
export -f copy_bin_scripts

find $bin_directory -type f -printf "%f\n" | parallel --max-args 1 copy_bin_scripts {}
