defaultIndent: "  "
indentPreamble: 1
lookForPreamble:
  .tex: 1
  .sty: 0
  .cls: 0
  .bib: 0
  STDIN: 1
removeTrailingWhitespace:
  beforeProcessing: 0
  afterProcessing: 1
indentAfterItems:
  itemize: 1
  itemize*: 1
  enumerate: 1
  enumerate*: 1
indentRules:
  item: 1
noAdditionalIndentGlobal:
  item: 1
indentAfterHeadings:
  textit:
    indentAfterThisHeading: 1
    level: 1
  footnote:
    indentAfterThisHeading: 1
    level: 1
noAdditionalIndent:
  textit: 1
  footnote: 1
